name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov
          extensions: imagick

      - name: PHP version
        run: php -v

      - name: Install dependencies
        run: composer install

      - name: Validate dependencies
        run: composer validate

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Run PHP Code sniffer
        run: vendor/bin/phpcs

      - name: Check doc header
        run: vendor/bin/docheader check src tests
