name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov
          extensions: imagick

      - name: PHP version
        run: php -v

      - name: Install dependencies
        run: composer install

      - name: Validate dependencies
        run: composer validate

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite=Unit

      - name: Run PHP Code sniffer
        run: vendor/bin/phpcs

      - name: Check doc header
        run: vendor/bin/docheader check migrations src tests

      - name: Run Deptrac analysis
        run: vendor/bin/deptrac

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 10
          postgresql user: ergonode
          postgresql password: 123

      - name: Run functional tests
        run: |
          composer test-build
          vendor/bin/phpunit --testsuite=Functional
        env:
          DATABASE_URL_SHOPWARE: pgsql://ergonode:123@localhost:5432/ergonode_test?serverVersion=10&charset=utf8
